INSERT INTO public.topics (
    id,
    domain,
    onion_layer,
    title,
    summary,
    architect_relevance,
    higher_systems,
    lower_foundations,
    production_risks,
    glue_before,
    glue_after,
    sort_order
)
VALUES
(
    'agentic_ai_control_plane',
    'Agentic AI',
    'Outer layer: Agentic AI',
    'AI Control Plane for Agentic Systems',
    'The runtime governance layer that manages AI policies, permissions, routing, model choices, tool access, evaluation, audit, and rollback.',
    'Architects must control runtime behavior because production AI behavior is shaped by prompts, policies, tools, memory, evaluators, and routing, not only the model.',
    ARRAY['Autonomous agents', 'RAG assistants', 'AI copilots', 'Multi-tool workflows'],
    ARRAY['Prompts', 'Context windows', 'Tool calling', 'Evaluators', 'Access control'],
    ARRAY['Silent behavior drift', 'Unsafe tool use', 'Untraceable decisions', 'No rollback path'],
    ARRAY['Prompting', 'Tool calling', 'Evaluation basics'],
    ARRAY['Agent governance', 'Runtime observability', 'AI operating model'],
    10
),
(
    'agent_tool_permissions',
    'Agentic AI',
    'Outer layer: Agentic AI',
    'Tool Use, Permissions, and Action Boundaries',
    'How AI systems call external tools and why every tool action needs explicit permission, scope, and failure handling.',
    'Architects must separate safe assistance from business-impacting action, otherwise agent demos become production liabilities.',
    ARRAY['Agentic workflows', 'AMS copilots', 'Procurement agents', 'Service desk automation'],
    ARRAY['Function calling', 'APIs', 'Authorization', 'Policy checks'],
    ARRAY['Unauthorized actions', 'Data leakage', 'Incorrect API calls', 'No approval boundary'],
    ARRAY['APIs', 'Tool calling'],
    ARRAY['Agent control plane', 'Human approval design'],
    20
),
(
    'agent_memory_state',
    'Agentic AI',
    'Outer layer: Agentic AI',
    'Agent Memory and Runtime State',
    'How AI systems preserve context, decisions, user preferences, intermediate state, and workflow history across interactions.',
    'Architects must know which memory should persist, expire, be audited, or never be stored.',
    ARRAY['Personalized copilots', 'Long-running agents', 'Case management assistants'],
    ARRAY['Context windows', 'Databases', 'Vector memory', 'Session state'],
    ARRAY['Stale memory', 'Privacy leakage', 'Wrong personalization', 'Unexplainable behavior'],
    ARRAY['Context windows', 'Embeddings'],
    ARRAY['Agent observability', 'Governance'],
    30
),
(
    'rag_architecture',
    'GenAI / LLM / RAG',
    'RAG, tools, memory, orchestration, evaluation',
    'RAG Architecture',
    'Retrieval Augmented Generation connects enterprise knowledge retrieval with LLM generation to produce grounded responses.',
    'Architects use RAG when business knowledge changes faster than model training or must stay inside enterprise boundaries.',
    ARRAY['Knowledge assistants', 'Engineering copilots', 'Policy assistants'],
    ARRAY['Embeddings', 'Chunking', 'Vector search', 'Prompt grounding'],
    ARRAY['Wrong retrieval', 'Hallucinated synthesis', 'Poor chunking', 'No source traceability'],
    ARRAY['Embeddings', 'Tokens'],
    ARRAY['Graph RAG', 'Evaluation'],
    40
),
(
    'embeddings_vector_search',
    'GenAI / LLM / RAG',
    'RAG, tools, memory, orchestration, evaluation',
    'Embeddings and Vector Search',
    'Embeddings convert text into numeric representations so similar meanings can be searched by distance.',
    'Architects must understand embeddings because retrieval quality often determines whether RAG succeeds or fails.',
    ARRAY['RAG systems', 'Semantic search', 'Recommendation', 'Duplicate detection'],
    ARRAY['Vectors', 'Distance metrics', 'Representation learning'],
    ARRAY['Bad semantic matches', 'Domain mismatch', 'Poor indexing', 'False confidence'],
    ARRAY['Tokens', 'Basic vectors'],
    ARRAY['Chunking', 'RAG architecture'],
    50
),
(
    'chunking_context_engineering',
    'GenAI / LLM / RAG',
    'RAG, tools, memory, orchestration, evaluation',
    'Chunking and Context Engineering',
    'Chunking decides how source documents are split and inserted into the model context.',
    'Architects must design context because models answer from what they see, not from what the enterprise owns somewhere else.',
    ARRAY['RAG assistants', 'Document intelligence', 'Legal and engineering knowledge systems'],
    ARRAY['Tokens', 'Context windows', 'Document structure'],
    ARRAY['Missing context', 'Fragmented evidence', 'Contradictory chunks', 'High token cost'],
    ARRAY['Tokens', 'Embeddings'],
    ARRAY['RAG evaluation', 'Prompt grounding'],
    60
),
(
    'prompting_as_control_surface',
    'GenAI / LLM / RAG',
    'RAG, tools, memory, orchestration, evaluation',
    'Prompting as a Control Surface',
    'Prompts define instructions, boundaries, output structure, reasoning style, and task framing for LLM behavior.',
    'Architects must treat prompts as versioned production assets, not casual text.',
    ARRAY['Chat assistants', 'Agents', 'Evaluation workflows', 'Structured extraction'],
    ARRAY['Tokens', 'Instruction following', 'Output schemas'],
    ARRAY['Prompt drift', 'Inconsistent output', 'Weak boundaries', 'No version history'],
    ARRAY['Tokens', 'LLM basics'],
    ARRAY['Control plane', 'Evaluation'],
    70
),
(
    'llm_evaluation_guardrails',
    'Evaluation / Governance',
    'RAG, tools, memory, orchestration, evaluation',
    'LLM Evaluation and Guardrails',
    'Evaluation measures whether AI outputs are correct, grounded, safe, useful, and aligned with the intended task.',
    'Architects need evaluation because demos are misleading unless behavior is measured under realistic failure conditions.',
    ARRAY['RAG systems', 'Agents', 'Enterprise copilots', 'AI governance'],
    ARRAY['Test sets', 'Rubrics', 'Ground truth', 'Human review'],
    ARRAY['Undetected hallucination', 'Unsafe response', 'Regression after prompt changes'],
    ARRAY['Prompting', 'RAG architecture'],
    ARRAY['AI governance', 'Production monitoring'],
    80
),
(
    'tokens_context_windows',
    'Transformers',
    'Tokens, embeddings, context windows, transformers',
    'Tokens and Context Windows',
    'Tokens are the units models read and generate; context windows define how much information the model can consider at once.',
    'Architects must understand token limits because cost, latency, recall, and answer quality are all affected by context design.',
    ARRAY['RAG', 'Prompting', 'Long-context assistants', 'Agents'],
    ARRAY['Text representation', 'Tokenization', 'Sequence models'],
    ARRAY['Context overflow', 'High cost', 'Lost instructions', 'Poor retrieval packing'],
    ARRAY['Basic text processing'],
    ARRAY['Embeddings', 'Transformers'],
    90
),
(
    'transformer_attention',
    'Transformers',
    'Tokens, embeddings, context windows, transformers',
    'Transformer Attention Intuition',
    'Attention lets a model weigh relationships between tokens so it can use relevant context while generating output.',
    'Architects do not need to derive transformers first, but they must understand why context, order, and attention patterns matter.',
    ARRAY['LLMs', 'Embedding models', 'Translation systems', 'Summarization'],
    ARRAY['Tokens', 'Vectors', 'Neural networks'],
    ARRAY['Overclaiming model understanding', 'Ignoring context limits', 'Weak explanation of LLM behavior'],
    ARRAY['Tokens', 'Embeddings'],
    ARRAY['LLM architecture', 'Fine-tuning basics'],
    100
),
(
    'neural_network_representations',
    'DL / NN',
    'Neural networks / deep learning',
    'Neural Networks as Representation Learners',
    'Neural networks learn internal representations that map inputs to useful outputs.',
    'Architects must explain why deep learning works differently from rule-based systems and why data quality matters.',
    ARRAY['LLMs', 'Computer vision', 'Speech models', 'Prediction systems'],
    ARRAY['Weights', 'Activation functions', 'Loss functions'],
    ARRAY['Overfitting', 'Poor generalization', 'Data leakage', 'Unclear model behavior'],
    ARRAY['Basic ML', 'Vectors'],
    ARRAY['Transformers', 'Training vs inference'],
    110
),
(
    'training_vs_inference',
    'DL / NN',
    'Neural networks / deep learning',
    'Training vs Inference',
    'Training learns model parameters from data; inference uses a trained model to produce outputs for new inputs.',
    'Architects must separate build-time cost and runtime cost, otherwise architecture and commercial estimates become wrong.',
    ARRAY['Model deployment', 'LLM serving', 'Fine-tuning', 'MLOps'],
    ARRAY['Parameters', 'Loss', 'Optimization', 'Hardware'],
    ARRAY['Wrong cost model', 'Latency issues', 'Incorrect infra sizing', 'Bad commercial assumptions'],
    ARRAY['Neural networks'],
    ARRAY['Model serving', 'MLOps'],
    120
),
(
    'overfitting_generalization',
    'ML Foundations',
    'ML foundations',
    'Overfitting and Generalization',
    'Overfitting happens when a model learns training data patterns too specifically and fails on new data.',
    'Architects must recognize overfitting because high demo accuracy can hide poor production performance.',
    ARRAY['Prediction systems', 'Quality inspection', 'Forecasting', 'Risk models'],
    ARRAY['Train/test split', 'Validation', 'Bias variance'],
    ARRAY['Demo success but production failure', 'Data leakage', 'Weak validation'],
    ARRAY['Basic supervised learning'],
    ARRAY['Evaluation', 'Model monitoring'],
    130
),
(
    'model_monitoring_drift',
    'Evaluation / Governance',
    'Evaluation / Governance',
    'Model Monitoring and Drift',
    'Drift happens when production data or business behavior changes after deployment.',
    'Architects must design monitoring because AI systems can degrade silently without code changes.',
    ARRAY['Production AI platforms', 'MLOps', 'LLMOps', 'AMS copilots'],
    ARRAY['Metrics', 'Baselines', 'Feedback loops', 'Data distributions'],
    ARRAY['Silent degradation', 'Missed incidents', 'Wrong business decisions'],
    ARRAY['Evaluation basics'],
    ARRAY['AI operating model', 'Governance'],
    140
),
(
    'ai_governance_operating_model',
    'Evaluation / Governance',
    'Evaluation / Governance',
    'AI Governance Operating Model',
    'The operating model defines ownership, review, accountability, escalation, measurement, and change control for AI systems.',
    'Architects must design not only the solution, but how it will be operated safely after go-live.',
    ARRAY['Enterprise AI programs', 'Agentic AI platforms', 'Regulated AI systems'],
    ARRAY['Risk management', 'Policies', 'Audit', 'Human accountability'],
    ARRAY['No ownership', 'Weak escalation', 'Compliance gaps', 'Uncontrolled runtime changes'],
    ARRAY['Evaluation', 'Control plane'],
    ARRAY['AI platform strategy', 'Enterprise governance'],
    150
)
ON CONFLICT (id) DO UPDATE SET
    domain = EXCLUDED.domain,
    onion_layer = EXCLUDED.onion_layer,
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    architect_relevance = EXCLUDED.architect_relevance,
    higher_systems = EXCLUDED.higher_systems,
    lower_foundations = EXCLUDED.lower_foundations,
    production_risks = EXCLUDED.production_risks,
    glue_before = EXCLUDED.glue_before,
    glue_after = EXCLUDED.glue_after,
    sort_order = EXCLUDED.sort_order,
    updated_at = NOW();